package com.azeroth.api.enums;

public enum ErrorCode {
    CLASE_NO_DISPONIBLE_PARA_RAZA,
    CLASE_NO_DISPONIBLE_PARA_FACCION,
    RAZA_NO_DISPONIBLE_PARA_FACCION,
    NOMBRE_JUGADOR_YA_EN_USO,
    HERMANDAD_FACION_NO_COINCIDE,
    JUGADOR_NO_ENCONTRADO,
}
